schema_version = 1
id = "com.github.Suxto.horizon-enhanced"
name = "Horizon Enhanced"
version = "0.1.0"
authors = ["Suxto <Suxto@outlook.com>"]
description = "Horizon theme for Zed, inspired by Horizon theme on VSCode."
repository = "https://github.com/Suxto/horizon-enhanced"
